### ISSUE TITLE
Develop input validation and a simple CLI or web interface 

### ISSUE THREAD

**Issue by Amoghh-Dixit** [Amoghh-Dixit/Assignment1_RSA#2]

**Comment by hemanthganji** [comment]
To develop a Boolean Logic Simulator with input validation and a simple Command-Line Interface (CLI), begin by clearly defining the problem: users need to input different logic gates (AND, OR, NOT, XOR) along with binary values (0 or 1) to compute the output. First, outline the program structure, including functions for each logic gate (e.g., and_gate, or_gate, not_gate, and xor_gate) to perform the respective logical operations. Implement input validation by creating functions that check if the entered gate type is valid and ensure the inputs are binary. In the main program loop, prompt users for the gate type and inputs, validate their entries, and display the computed results. Utilize a continuous loop to allow repeated operations until the user opts to exit the program. Additionally, you can implement error handling to improve user experience and ensure the program operates smoothly even with invalid inputs. Once completed, test the simulator for each gate and its corresponding inputs, and use Git for version control to manage and track changes to your code.
